import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

function syncToVault() {
	const targetDir = "/Users/longhai/Library/Mobile Documents/iCloud~md~obsidian/Documents/龙海的数字花园/.obsidian/plugins/longhai-podscript";
	if (fs.existsSync(targetDir)) {
		for (const file of ["main.js", "styles.css", "manifest.json"]) {
			if (fs.existsSync(file)) {
				fs.copyFileSync(file, path.join(targetDir, file));
			}
		}
		console.log("⚡ [esbuild] Synced build artifacts to Obsidian vault plugins directory.");
	}
}

if (prod) {
	await context.rebuild();
	syncToVault();
	process.exit(0);
} else {
	await context.watch();
}
